#!/usr/bin/env python3
import os
import sys
import argparse
import shutil
import re

OS_RELEASE_PATH = "/etc/os-release"
HOSTNAME_PATH = "/etc/hostname"
ISSUE_PATH = "/etc/issue"

def check_root():
    if os.geteuid() != 0:
        print("Error: This script must be run as root (sudo).", file=sys.stderr)
        sys.exit(1)

def parse_os_release():
    if not os.path.exists(OS_RELEASE_PATH):
        return {}
    data = {}
    with open(OS_RELEASE_PATH, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, val = line.split("=", 1)
                # Strip quotes if present
                val = val.strip('"\'')
                data[key] = val
    return data

def write_os_release(data):
    # Backup first
    backup_path = OS_RELEASE_PATH + ".bak"
    if not os.path.exists(backup_path):
        shutil.copy2(OS_RELEASE_PATH, backup_path)
        print(f"Backed up {OS_RELEASE_PATH} to {backup_path}")

    with open(OS_RELEASE_PATH, "w") as f:
        for k, v in data.items():
            # If value contains spaces, wrap it in double quotes
            if " " in v or not v.isalnum():
                f.write(f'{k}="{v}"\n')
            else:
                f.write(f'{k}={v}\n')

def get_real_user():
    """Determine the real (non-root) user, even when running under sudo."""
    username = os.environ.get("SUDO_USER")
    if not username:
        try:
            import subprocess
            username = subprocess.check_output("logname", text=True).strip()
        except Exception:
            try:
                username = os.getlogin()
            except Exception:
                username = None

    if not username or username == "root":
        if os.path.exists("/home"):
            dirs = [d for d in os.listdir("/home")
                    if os.path.isdir(os.path.join("/home", d)) and d != "lost+found"]
            if dirs:
                username = dirs[0]

    if not username or username == "root":
        return None, None

    user_home = os.path.expanduser(f"~{username}")
    return username, user_home

def ensure_fastfetch_config(username, user_home):
    """
    Ensure ~/.config/fastfetch/ exists and config.jsonc is present.
    Creates the directory and generates the config if needed.
    Returns the path to config.jsonc, or None on failure.
    """
    fastfetch_dir = os.path.join(user_home, ".config/fastfetch")
    fastfetch_conf = os.path.join(fastfetch_dir, "config.jsonc")

    # Create the directory if it doesn't exist
    if not os.path.exists(fastfetch_dir):
        os.makedirs(fastfetch_dir, exist_ok=True)
        # Fix ownership so user owns their own config dir
        try:
            import pwd
            pw = pwd.getpwnam(username)
            os.chown(fastfetch_dir, pw.pw_uid, pw.pw_gid)
        except Exception:
            pass
        print(f"Created fastfetch config directory: {fastfetch_dir}")

    # Generate config.jsonc if it doesn't exist
    if not os.path.exists(fastfetch_conf):
        if shutil.which("fastfetch"):
            ret = os.system(f"su - {username} -c 'fastfetch --gen-config'")
            if ret != 0 or not os.path.exists(fastfetch_conf):
                # Write a minimal default config
                _write_minimal_fastfetch_config(fastfetch_conf, username)
        else:
            # fastfetch not installed — write a minimal config anyway
            _write_minimal_fastfetch_config(fastfetch_conf, username)

    return fastfetch_conf if os.path.exists(fastfetch_conf) else None

def _write_minimal_fastfetch_config(path, username):
    """Write a minimal fastfetch config.jsonc."""
    minimal = """{
  // Fastfetch configuration — generated by makeuros
  "logo": {},
  "modules": [
    "title",
    "separator",
    "os",
    "host",
    "kernel",
    "uptime",
    "packages",
    "shell",
    "display",
    "de",
    "wm",
    "terminal",
    "cpu",
    "gpu",
    "memory",
    "disk",
    "battery",
    "locale",
    "break",
    "colors"
  ]
}
"""
    with open(path, "w") as f:
        f.write(minimal)
    try:
        import pwd
        pw = pwd.getpwnam(username)
        os.chown(path, pw.pw_uid, pw.pw_gid)
    except Exception:
        pass
    print(f"Created minimal fastfetch config at {path}")

def update_fetch_logo(logo_path, username, user_home):
    """Update fastfetch and neofetch configs to use the given logo/image path."""

    # --- Fastfetch ---
    fastfetch_conf = ensure_fastfetch_config(username, user_home)
    if fastfetch_conf:
        try:
            with open(fastfetch_conf, "r") as f:
                content = f.read()

            if '"logo"' in content:
                # Replace existing logo block — update or insert source/type
                if '"source"' in content:
                    content = re.sub(
                        r'("logo"\s*:\s*\{[^}]*"source"\s*:\s*")[^"]*(")',
                        r'\g<1>' + logo_path + r'\g<2>',
                        content
                    )
                else:
                    content = re.sub(
                        r'("logo"\s*:\s*\{)',
                        r'\g<1>\n    "source": "' + logo_path + '",\n    "type": "file",',
                        content
                    )
                if '"type"' not in content:
                    content = re.sub(
                        r'("logo"\s*:\s*\{)',
                        r'\g<1>\n    "type": "file",',
                        content
                    )
                else:
                    content = re.sub(
                        r'("logo"\s*:\s*\{[^}]*"type"\s*:\s*")[^"]*(")',
                        r'\g<1>file\g<2>',
                        content
                    )
            else:
                replacement = '{\n  "logo": {\n    "source": "' + logo_path + '",\n    "type": "file"\n  },'
                content = content.replace('{', replacement, 1)

            with open(fastfetch_conf, "w") as f:
                f.write(content)
            print(f"Updated fastfetch config at {fastfetch_conf} to use custom logo.")
        except Exception as e:
            print(f"Failed to update fastfetch config: {e}")

    # --- Neofetch ---
    neofetch_conf = os.path.join(user_home, ".config/neofetch/config.conf")
    if os.path.exists(neofetch_conf):
        try:
            with open(neofetch_conf, "r") as f:
                lines = f.readlines()

            for i, line in enumerate(lines):
                if line.strip().startswith("image_source="):
                    lines[i] = f'image_source="{logo_path}"\n'
                elif line.strip().startswith("image_backend="):
                    lines[i] = 'image_backend="ascii"\n'

            with open(neofetch_conf, "w") as f:
                f.writelines(lines)
            print(f"Updated neofetch config at {neofetch_conf} to use custom logo.")
        except Exception as e:
            print(f"Failed to update neofetch config: {e}")

def update_fetch_os_info(username, user_home, color=None):
    """
    Update fastfetch config with OS info from /etc/os-release and optional color.
    Ensures the custom OS name, ID, and pretty name are reflected.
    """
    data = parse_os_release()
    os_name = data.get("NAME", "")
    os_id = data.get("ID", "")
    pretty_name = data.get("PRETTY_NAME", "")

    # --- Fastfetch ---
    fastfetch_conf = ensure_fastfetch_config(username, user_home)
    if fastfetch_conf:
        try:
            with open(fastfetch_conf, "r") as f:
                content = f.read()

            # Update title module to show custom OS name
            if '"title"' in content:
                # title module exists, ensure it uses os-release data
                pass
            else:
                # Add title module at the beginning of modules array
                content = re.sub(
                    r'("modules"\s*:\s*\[\s*)',
                    r'\1\n    "title",',
                    content
                )

            # Set custom title format if NAME is set
            if os_name:
                title_format = f'"titleFormat": "{os_name}"'
                if '"titleFormat"' in content:
                    content = re.sub(
                        r'("titleFormat"\s*:\s*")[^"]*(")',
                        r'\g<1>' + os_name + r'\g<2>',
                        content
                    )
                else:
                    # Insert after opening brace or after logo block
                    content = re.sub(
                        r'(\{)',
                        r'\1\n  ' + title_format + ',',
                        content,
                        count=1
                    )

            # Ensure os module is present to show ID
            if '"os"' not in content:
                content = re.sub(
                    r'("modules"\s*:\s*\[\s*)',
                    r'\1\n    "os",',
                    content
                )

            # Handle color if provided
            if color:
                # Remove old colorScheme if present
                if '"colorScheme"' in content:
                    content = re.sub(
                        r',?\s*"colorScheme"\s*:\s*"[^"]*"',
                        '',
                        content
                    )

                # Check for display OBJECT (not the "display" string in modules array)
                has_display_obj = '"display": {' in content

                if has_display_obj and '"color"' in content:
                    # Update existing display.color
                    content = re.sub(
                        r'("display"\s*:\s*\{[^}]*"color"\s*:\s*")[^"]*(")',
                        r'\g<1>' + color + r'\g<2>',
                        content
                    )
                elif has_display_obj:
                    # Add color to existing display object
                    content = re.sub(
                        r'("display"\s*:\s*\{)',
                        r'\1\n    "color": "' + color + '",',
                        content
                    )
                else:
                    # Add display object with color after opening brace
                    content = re.sub(
                        r'(\{)',
                        r'\1\n  "display": {\n    "color": "' + color + '"\n  },',
                        content,
                        count=1
                    )

            with open(fastfetch_conf, "w") as f:
                f.write(content)
            print(f"Updated fastfetch config at {fastfetch_conf} with OS info: {os_name} ({os_id})" + (f", color: {color}" if color else ""))
        except Exception as e:
            print(f"Failed to update fastfetch OS info config: {e}")

def set_hostname(new_hostname):
    check_root()
    # Backup first
    backup_path = HOSTNAME_PATH + ".bak"
    if not os.path.exists(backup_path):
        shutil.copy2(HOSTNAME_PATH, backup_path)
        print(f"Backed up {HOSTNAME_PATH} to {backup_path}")

    with open(HOSTNAME_PATH, "w") as f:
        f.write(new_hostname.strip() + "\n")

    # Try to set hostname in current session as well
    os.system(f"hostnamectl set-hostname {new_hostname}")
    print(f"Hostname updated to: {new_hostname}")

def install_package(pkg):
    print(f"Resolving the best installation path for: {pkg}...")
    import shutil
    import subprocess

    # 1. Custom overrides for tricky applications
    if pkg.lower() == "ollama":
        print("Detected 'ollama'. Checking installation options...")
        if shutil.which("yay"):
            print("Installing ollama via 'yay' (AUR)...")
            res = os.system("yay -S --noconfirm ollama")
            if res == 0:
                print("ollama installed successfully via yay!")
                return
        if shutil.which("curl"):
            print("Installing ollama via official curl installer script...")
            res = os.system("curl -fsSL https://ollama.com/install.sh | sh")
            if res == 0:
                print("ollama installed successfully via curl script!")
                return

    # 2. Check official Arch repositories (pacman)
    if shutil.which("pacman"):
        check_pacman = subprocess.run(["pacman", "-Si", pkg], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if check_pacman.returncode == 0:
            print(f"Package '{pkg}' found in official repositories. Installing via pacman...")
            res = os.system(f"sudo pacman -S --noconfirm {pkg}")
            if res == 0:
                print(f"Successfully installed {pkg} via pacman!")
                return

    # 3. Check AUR (yay)
    if shutil.which("yay"):
        print(f"Checking if '{pkg}' is available in the AUR...")
        check_aur = subprocess.run(["yay", "-Si", pkg], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if check_aur.returncode == 0:
            print(f"Package '{pkg}' found in AUR. Installing via yay...")
            res = os.system(f"yay -S --noconfirm {pkg}")
            if res == 0:
                print(f"Successfully installed {pkg} via yay!")
                return

    # 4. Check Flatpak
    if shutil.which("flatpak"):
        print(f"Checking if '{pkg}' is available on Flathub...")
        check_flatpak = subprocess.run(["flatpak", "search", pkg], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if check_flatpak.returncode == 0 and pkg.lower() in check_flatpak.stdout.lower():
            app_id = ""
            for line in check_flatpak.stdout.split("\n"):
                parts = [p.strip() for p in line.split("\t") if p.strip()]
                if len(parts) >= 2 and (pkg.lower() in parts[0].lower() or pkg.lower() in parts[1].lower()):
                    app_id = parts[1]
                    break
            if app_id:
                print(f"Package '{pkg}' found on Flathub (ID: {app_id}). Installing via Flatpak...")
                res = os.system(f"flatpak install -y flathub {app_id}")
                if res == 0:
                    print(f"Successfully installed {pkg} via Flatpak!")
                    return

    # 5. Check Snap
    if shutil.which("snap"):
        print(f"Checking if '{pkg}' is available on Snap Store...")
        check_snap = subprocess.run(["snap", "info", pkg], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if check_snap.returncode == 0:
            print(f"Package '{pkg}' found on Snap Store. Installing via snap...")
            res = os.system(f"sudo snap install {pkg}")
            if res == 0:
                print(f"Successfully installed {pkg} via Snap!")
                return

    # 6. Check pip
    if shutil.which("pip"):
        print(f"Checking if '{pkg}' is available on PyPI (pip)...")
        check_pip_dry = subprocess.run(["pip", "install", pkg, "--dry-run"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if check_pip_dry.returncode == 0:
            print(f"Package '{pkg}' found on PyPI. Installing via pip...")
            res = os.system(f"pip install --user {pkg}")
            if res == 0:
                print(f"Successfully installed {pkg} via pip!")
                return

    # 7. Known developer install scripts
    common_scripts = {
        "rustup": "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
        "bun": "curl -fsSL https://bun.sh/install | sh",
        "deno": "curl -fsSL https://deno.land/install.sh | sh",
        "nvm": "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash",
        "pipx": "python3 -m pip install --user pipx && python3 -m pipx ensurepath"
    }

    if pkg.lower() in common_scripts:
        script = common_scripts[pkg.lower()]
        print(f"Found developer install script for '{pkg}'. Running installer...")
        res = os.system(script)
        if res == 0:
            print(f"Successfully installed {pkg}!")
            return

    print(f"Error: Could not find a suitable installation method for '{pkg}'. Try installing it manually.")
    sys.exit(1)

def show_specs():
    print("=" * 50)
    print("                 SYSTEM SPECIFICATIONS                 ")
    print("=" * 50)

    # 1. Print Custom OS variables
    data = parse_os_release()
    print(f"OS Custom Name  : {data.get('NAME', 'Not set (Arch Linux default)')}")
    print(f"OS Custom ID    : {data.get('ID', 'Not set')}")
    print(f"OS Pretty Name  : {data.get('PRETTY_NAME', 'Not set')}")
    print(f"OS Logo File    : {data.get('LOGO', 'Default logo')}")

    if os.path.exists(HOSTNAME_PATH):
        with open(HOSTNAME_PATH, "r") as f:
            print(f"System Hostname : {f.read().strip()}")

    # 2. Print Hardware/System Specs
    print("-" * 50)
    try:
        import platform
        print(f"Kernel Version  : {platform.release()}")
        print(f"Processor       : {platform.processor() or 'Unknown'}")

        with open("/proc/meminfo", "r") as f:
            for line in f:
                if "MemTotal" in line:
                    total_kb = int(line.split()[1])
                    print(f"Total RAM       : {total_kb / 1024 / 1024:.2f} GB")
                    break

        with open("/proc/cpuinfo", "r") as f:
            for line in f:
                if "model name" in line:
                    model = line.split(":", 1)[1].strip()
                    print(f"CPU Model       : {model}")
                    break

        import shutil
        total, used, free = shutil.disk_usage("/")
        print(f"Root Disk Space : {total / (1024**3):.2f} GB total ({free / (1024**3):.2f} GB free)")
    except Exception as e:
        print(f"Could not retrieve all hardware specs: {e}")
    print("=" * 50)

def run_interactive():
    print("==================================================")
    print("        makeuros Customization Wizard             ")
    print("==================================================")

    if os.geteuid() != 0:
        print("\nNote: This wizard needs sudo privileges to write system changes.")
        print("Please rerun with: sudo makeuros --interactive")
        sys.exit(1)

    name = input("Enter OS Name (e.g., SpaceOS) [Leave blank to skip]: ").strip()
    os_id = input("Enter OS ID / logo path (lowercase, e.g., spaceos or /path/to/logo.png) [Leave blank to skip]: ").strip()
    pretty = input("Enter Pretty Name (e.g., SpaceOS GNU/Linux) [Leave blank to skip]: ").strip()
    color = input("Enter color for fastfetch/neofetch (e.g., cyan, red, 4) [Leave blank to skip]: ").strip()
    hostname = input("Enter Hostname [Leave blank to skip]: ").strip()
    home_url = input("Enter Homepage URL [Leave blank to skip]: ").strip()
    lsb = input("Do you want to update /etc/lsb-release as well? (y/n) [n]: ").strip().lower() == "y"

    cmd = "sudo makeuros"
    if name: cmd += f' --name "{name}"'
    if os_id: cmd += f' --id "{os_id}"'
    if pretty: cmd += f' --pretty-name "{pretty}"'
    if color: cmd += f' --color "{color}"'
    if hostname: cmd += f' --hostname "{hostname}"'
    if home_url: cmd += f' --home-url "{home_url}"'
    if lsb: cmd += ' --lsb-release'

    if cmd == "sudo makeuros":
        print("No modifications chosen. Exiting.")
        return

    print(f"\nRunning modification: {cmd}")
    os.system(cmd)

def write_lsb_release(name, os_id, pretty):
    lsb_path = "/etc/lsb-release"
    backup_path = lsb_path + ".bak"
    if os.path.exists(lsb_path) and not os.path.exists(backup_path):
        shutil.copy2(lsb_path, backup_path)
        print(f"Backed up {lsb_path} to {backup_path}")

    with open(lsb_path, "w") as f:
        f.write(f"DISTRIB_ID={os_id.upper()}\n")
        f.write(f"DISTRIB_RELEASE=1.0\n")
        f.write(f"DISTRIB_CODENAME={os_id}\n")
        f.write(f'DISTRIB_DESCRIPTION="{pretty}"\n')
    print(f"Updated {lsb_path} successfully!")

def main():
    parser = argparse.ArgumentParser(description="makeuros: Customize your Arch Linux system identity")
    parser.add_argument("--name", help="Set the OS Name (e.g. MySuperOS)")
    parser.add_argument("--id", help=(
        "Set the OS ID (lowercase, e.g. mysuperos). "
        "If a file path is given, it is used as the custom logo for fastfetch/neofetch "
        "and ~/.config/fastfetch/ is auto-created if needed."
    ))
    parser.add_argument("--pretty-name", help="Set the Pretty Name (e.g. MySuperOS GNU/Linux)")
    parser.add_argument("--hostname", help="Set the system hostname")
    parser.add_argument("--color", help=(
        "Set the accent color for fastfetch/neofetch output. "
        "Accepts a color name (e.g. cyan, red, magenta) or an ANSI number (0-15)."
    ))
    parser.add_argument("--home-url", help="Set the Home Page URL")
    parser.add_argument("--reset", action="store_true", help="Restore /etc/os-release and /etc/hostname from backups")
    parser.add_argument("--install", help="Install a package automatically using the best tool (pacman, yay, curl script, etc.)")
    parser.add_argument("--interactive", action="store_true", help="Launch interactive setup menu to customize everything")
    parser.add_argument("--show-specs", action="store_true", help="Display summary of custom OS properties and hardware specifications")
    parser.add_argument("--lsb-release", action="store_true", help="Also generate /etc/lsb-release for Debian/Ubuntu compatibility layers")

    args = parser.parse_args()

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)

    if args.install:
        install_package(args.install)
        sys.exit(0)

    if args.show_specs or (len(sys.argv) == 2 and sys.argv[1] == "--show-specs"):
        show_specs()
        sys.exit(0)

    if args.interactive:
        run_interactive()
        sys.exit(0)

    # --color and --id (logo path) both need to know the real user but NOT necessarily root
    # However writing /etc/os-release does. We'll get the user early for fetch updates.
    username, user_home = get_real_user()

    # Handle --color (no root needed for user config files)
    if args.color:
        if username and user_home:
            update_fetch_os_info(username, user_home, color=args.color)
        else:
            print("Warning: Could not determine the real user home directory. Skipping fetch color update.")

    # Everything below modifies system files and needs root
    check_root()

    if args.reset:
        restored = False
        for path in [OS_RELEASE_PATH, HOSTNAME_PATH]:
            bak = path + ".bak"
            if os.path.exists(bak):
                shutil.copy2(bak, path)
                print(f"Restored {path} from {bak}")
                restored = True
        if not restored:
            print("No backups found to restore.")
        sys.exit(0)

    data = parse_os_release()

    modified = False

    if args.name:
        data["NAME"] = args.name
        modified = True

    if args.id:
        expanded = os.path.expanduser(args.id)
        if os.path.exists(expanded):
            # It's a file/path — treat as custom logo
            logo_path = os.path.abspath(expanded)
            data["ID"] = "custom_os"
            data["LOGO"] = logo_path
            if username and user_home:
                update_fetch_logo(logo_path, username, user_home)
            else:
                print("Warning: Could not determine user home. Skipping fastfetch/neofetch logo update.")
        else:
            # Plain OS ID string — still ensure fastfetch config dir/file exists
            data["ID"] = args.id
            if username and user_home:
                ensure_fastfetch_config(username, user_home)
        modified = True

    if args.pretty_name:
        data["PRETTY_NAME"] = args.pretty_name
        modified = True

    if args.home_url:
        data["HOME_URL"] = args.home_url
        modified = True

    if modified:
        write_os_release(data)
        print("Updated /etc/os-release successfully!")

        # Update fastfetch/neofetch with new OS info system-wide
        if username and user_home:
            update_fetch_os_info(username, user_home, color=args.color)

        if args.lsb_release:
            name_val = data.get("NAME", "SpaceOS")
            id_val = data.get("ID", "spaceos")
            pretty_val = data.get("PRETTY_NAME", f"{name_val} GNU/Linux")
            write_lsb_release(name_val, id_val, pretty_val)

        if "PRETTY_NAME" in data:
            with open(ISSUE_PATH, "w") as f:
                f.write(f"{data['PRETTY_NAME']} (\\l)\n\n")

    if args.hostname:
        set_hostname(args.hostname)

if __name__ == "__main__":
    main()
